library("rpart")
library("rattle")
library(rpart.plot)
library(RColorBrewer)
data<-read.csv("C:/Users/kb/Desktop/i.csv")
str(data)
d_data<-as.data.frame(data)
printcp(tree)
tree <- rpart(d_data$class ~d_data$buying+d_data$maint+d_data$doors+d_data$persons+d_data$lug_boot+d_data$safety,data=d_data,method="class")
fancyRpartPlot(tree, uniform=TRUE)
text(tree,pretty=0)